### ISSUE TITLE
Identify the project associated with each milestone

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/timeline#4]
When there is more than one project displayed then it would  be good to know which milestone goes with which project, but this may be difficult in the interface (and in manipulating the data)

Having the project name in the text at the top of the page for the individual Milestone would be good.

Possibly having it in the marker

Possibly colour coding, but I think this is not easy?

**Comment by kindly** [comment]
I have added the project name in brackets at the end of the title.  Is that good enough?

**Comment by caprenter** [comment]
yes thanks!
