### ISSUE TITLE
Some milestones are a month early

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/timeline#7]
I'm seeing some milestones showing a month early on timeliner - others are correct tho. I've tried all projects and noticed some deliverables were basically a month early. Filtering to just a single project seems to also show some a month early?

However some are shown at the correct date as well...

**Comment by kindly** [comment]
Could you give an example, or better still see if the api calls are returning the correct results.

**Comment by caprenter** [comment]
My api call seems to give me the correct dates for e.g. Grant Nav deliverables in my redmine, but the timeline shows them a month early

**Comment by kindly** [comment]
fixed in 179e1dea5ec16
All dates should have been a month early.  Stupid javascript dates are from 0-11.   Can you see if you can find ones now that late, it may be ok now though as I do not know what timeliner does with 0.

**Comment by caprenter** [comment]
I think this is all ok now. Thanks!
